import { z } from 'zod';
import * as publicOrderTrackingService from '../services/publicOrderTrackingService.js';
import { verifyTrackingToken } from '../utils/trackingTokenUtils.js';
import { ApiError } from '../utils/response.js';
import { ok } from '../utils/response.js';

// Both endpoints accept either a signed token (t=...) — what the tracking
// link generated by admin's "Lacak Order" action carries — or the raw
// noWa+invoiceId pair directly, for callers that already have both.
const trackingQuerySchema = z
  .object({
    t: z.string().optional(),
    noWa: z.string().optional(),
    invoiceId: z.string().optional(),
  })
  .refine((v) => v.t || (v.noWa && v.invoiceId), {
    message: 'Provide either t, or both noWa and invoiceId',
  });

const approveSchema = z
  .object({
    t: z.string().optional(),
    noWa: z.string().optional(),
    invoiceId: z.string().optional(),
    note: z.string().optional(),
  })
  .refine((v) => v.t || (v.noWa && v.invoiceId), {
    message: 'Provide either t, or both noWa and invoiceId',
  });

function resolveCredentials({ t, noWa, invoiceId }) {
  if (t) {
    const decoded = verifyTrackingToken(t);
    if (!decoded) throw new ApiError(404, 'Order tidak ditemukan');
    return decoded;
  }
  return { noWa, invoiceId };
}

export async function timeline(req, res, next) {
  try {
    const parsed = trackingQuerySchema.parse(req.query);
    const { noWa, invoiceId } = resolveCredentials(parsed);
    ok(res, await publicOrderTrackingService.getPublicOrderTimeline(noWa, invoiceId));
  } catch (err) {
    next(err);
  }
}

export async function approveDesign(req, res, next) {
  try {
    const parsed = approveSchema.parse(req.body);
    const { noWa, invoiceId } = resolveCredentials(parsed);
    ok(res, await publicOrderTrackingService.approveDesignPublic(noWa, invoiceId, parsed.note));
  } catch (err) {
    next(err);
  }
}
